import { ListItem, Tab, Tabs, Typography } from "@mui/material";
import { Box } from "@mui/system";
import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import List from "@mui/material/List";
import ListItemButton from "@mui/material/ListItemButton";
import ListItemIcon from "@mui/material/ListItemIcon";
import ListItemText from "@mui/material/ListItemText";
import StarBorder from "@mui/icons-material/StarBorder";
import PersonAddIcon from "@mui/icons-material/PersonAdd";
import PeopleIcon from "@mui/icons-material/People";
import SubscriptionsIcon from "@mui/icons-material/Subscriptions";
import VideogameAssetIcon from "@mui/icons-material/VideogameAsset";
import EditIcon from "@mui/icons-material/Edit";
import FastRewindIcon from "@mui/icons-material/FastRewind";
import CodeIcon from "@mui/icons-material/Code";
import LibraryMusicIcon from "@mui/icons-material/LibraryMusic";

function BiographyList(props) {
  const items = [
    {
      icon: <CodeIcon />,
      primary: "Webサイト / Webアプリを作る (2007-)",
      secondary: "HTML / CSS(SCSS) / JavaScript / TypeScript / React",
    },
    {
      icon: <FastRewindIcon />,
      primary: "音楽を作る (2011-)",
      childItems: [
        {
          icon: <StarBorder />,
          primary: "ex. happyender girl (2015-2019, 2019-)",
          secondary: "ボーカロイド音楽サークル",
        },
        {
          icon: <StarBorder />,
          primary: "Bandcamp",
        },
        {
          icon: <StarBorder />,
          primary: "Spotify",
        },
        {
          icon: <StarBorder />,
          primary: "SoundCloud",
        },
        {
          icon: <StarBorder />,
          primary: "YouTube",
        },
        {
          icon: <StarBorder />,
          primary: "ニコニコ動画",
        },
      ],
    },
    {
      icon: <LibraryMusicIcon />,
      primary: "音楽を聴く (2007-)",
      childItems: [
        {
          icon: <StarBorder />,
          primary: "All you need is black earphone (?) (2012-)",
          secondary: "あたまのわるい音楽ブログ",
        },
      ],
    },
    {
      icon: <EditIcon />,
      primary: "小説を書く (2007-)",
      childItems: [
        {
          icon: <StarBorder />,
          primary: "pixiv",
          secondary: "東方二次創作",
        },
      ],
    },
    {
      icon: <VideogameAssetIcon />,
      primary: "ゲームを作る (2009-)",
    },
    {
      icon: <SubscriptionsIcon />,
      primary: "VTuberになる (2019)",
    },
    {
      icon: <PersonAddIcon />,
      primary: "うちのこを愛でる (2019-)",
      childItems: [
        {
          icon: <StarBorder />,
          primary: "VRoid Hub",
          secondary: "東方二次創作",
        },
        {
          icon: <StarBorder />,
          primary: "meish.me",
          secondary: "東方二次創作",
        },
      ],
    },
    {
      icon: <PeopleIcon />,
      primary: "VRChatをやる (2020-)",
    },
  ];
  return (
    <List>
      {items.map((item) => {
        return (
          <>
            <ListItemButton key={item.primary} sx={{ pt: 0, pb: 0, mt: 6 }}>
              <ListItemIcon>{item.icon}</ListItemIcon>
              <ListItemText primary={item.primary} secondary={item.secondary} />
            </ListItemButton>
            {item.childItems && item.childItems?.length > 0 && (
              <List component="div" disablePadding>
                {item.childItems.map((childItem) => {
                  return (
                    <ListItemButton
                      sx={{ pl: 4, pt: 0, pb: 0 }}
                      key={childItem.primary}
                    >
                      <ListItemIcon>{childItem.icon}</ListItemIcon>
                      <ListItemText
                        primary={childItem.primary}
                        secondary={childItem.secondary}
                      />
                    </ListItemButton>
                  );
                })}
              </List>
            )}
          </>
        );
      })}
    </List>
  );
}

function TabPanel(props) {
  const { children, value, index, ...other } = props;

  return (
    <div role="tabpanel" hidden={value !== index} {...other}>
      {value === index && (
        <Box sx={{ p: 3 }}>
          <Typography>{children}</Typography>
        </Box>
      )}
    </div>
  );
}

const Home: NextPage = () => {
  const [value, setValue] = useState(0);
  const [open, setOpen] = useState(true);

  const handleClick = () => {
    setOpen(!open);
  };
  const handleChange = (event, newValue) => {
    setValue(newValue);
  };
  return (
    <div style={{ width: "50%" }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box sx={{ borderBottom: 1, borderColor: "divider" }}>
        <Tabs
          value={value}
          onChange={handleChange}
          aria-label="basic tabs example"
        >
          <Tab label="cicada_sss" />
          <Tab label="ex. happyender girl" />
        </Tabs>
      </Box>
      <TabPanel value={value} index={0}>
        [画像]
        <br />
        <Typography variant="h4" component="h2">
          蝉暮せせせ / cicada_sss
        </Typography>
        <Typography variant="body1">
          インターネットをやる、好きなバンドを追うなど活動は多岐に渡る。
          <br />
          大変マイペース。
        </Typography>
        <Typography variant="h5" component="h2">
          # 活動内容
        </Typography>
        <BiographyList />
      </TabPanel>
      <TabPanel value={value} index={1}>
        happyend recordings [画像] ex. happyender girl produced by 蝉暮せせせ /
        cicada_sss starring 初音ミク distributed by happyend recordings #
        Biography ex. happyender girlはボーカロイド音楽サークルです。 ex.
        happyender girl is Japanese youthful music group.
        数回の名義の変遷を経ています。 From 2015 as happyender girl. From 2019
        as ex. happyender girl. # Discography mixitup [画像] 曲目
      </TabPanel>
    </div>
  );
};

export default Home;
